version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo No Build Commands
  build:
    commands:
      - echo Build started on `date`
      - mvn clean test -DargLine="-Dkarate.env=dev"
  post_build:
    commands:
      - echo Build completed on `date`
reports:
  CucumberReportsTests:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports/src.test.java.com.iwe.test.study-datalake.json'
    file-format: CucumberJson
  CucumberReportsClasses:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports/target.test-classes.com.iwe.test.study-datalake.json'  
    file-format: CucumberJson      
cache:
  paths:
    - '/root/.m2/**/*'